---
- name: Initialize ManageIQ Tenant Quotas
  hosts: all
  gather_facts: false
  
  tasks:
    - name: Execute initialization script
      shell: |
        /var/www/miq/vmdb/bin/rails runner /opt/manageiq/custom_scripts/initialize_tenant_quotas.rb \
          {{ tenant_id }} {{ windows_licenses }} {{ rhel_licenses }} {{ backup_quota_gb }}
      register: result
      failed_when: "'ERROR' in result.stdout"

    - name: Display result
      debug:
        msg: "{{ result.stdout_lines }}"