---
- name: Sync ManageIQ Tenant Usage
  hosts: all
  gather_facts: false
  
  tasks:
    - name: Get list of tenants with quotas
      shell: |
        /var/www/miq/vmdb/bin/rails runner - <<'RUBY'
        tenant_ids = CloudTenant.joins(:cloud_resource_quotas)
          .where(cloud_resource_quotas: { service_name: "License" })
          .distinct
          .pluck(:id)
        puts tenant_ids.join(',')
        RUBY
      register: tenant_ids_raw
      changed_when: false

    - name: Parse tenant IDs
      set_fact:
        tenant_ids: "{{ tenant_ids_raw.stdout.split(',') | select() | list }}"

    - name: Display tenants to sync
      debug:
        msg: "Will sync {{ tenant_ids | length }} tenants"

    - name: Sync each tenant
      shell: |
        /var/www/miq/vmdb/bin/rails runner /opt/manageiq/custom_scripts/update_usage.rb {{ item }}
      loop: "{{ tenant_ids }}"
      when: tenant_ids | length > 0